apps/compras/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.compras.views import *

app_name='compras'
urlpatterns=[
    url(r'^cancel/(?P<idPedido>\w+)',cancelarPedido,name="cancel"),
    url(r'^aceptar/(?P<idPedido>\w+)',recibirPedido,name="aceptar"),
    url(r'^index',verpedidos,name="index"),
    url(r'^realizarCompras',agregarPedido,name="reCom"),
    url(r'^add/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', agregarLinea,name="add"),
    url(r'^editar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', editarLinea,name="editarLinea"),
    url(r'^borrar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', borrarLinea,name="borrarLinea"),
    #url(r'^addPedido', agregarPedido, name="addP"),
    url(r'^pedir/(?P<idPedido>\w+)/(?P<idProveedor>\w+)/', lineapedido, name="lin"),
    url(r'^cancelar/(?P<idPedido>\w+)/', cancelar, name="cancelar"),
    url(r'^verDetalle/(?P<idPedido>\w+)/', verDetalle, name="verDetalle"),
    url(r'^gestionarPedidos',PedidosList,name="gesPed"),
    
    path(
    	'proveedor/', 
    	proveedor_list,
    	name='proveedor-list'
    ),
    path(
    	'proveedor/create/',
    	proveedor_create,
    	name='proveedor-create'
    ),
    path(
        'proveedor/update/<int:pk>',
        proveedor_update,
        name='proveedor-update'
    ),
    path(
        'proveedor/delete/<int:pk>',
        proveedor_delete,
        name='proveedor-delete'
    ),


    path(
    	'articulo/', 
    	articulo_list,
    	name='articulo-list'
    ),
    path(
    	'articulo/create/',
    	articulo_create,
    	name='articulo-create'
    ),
    path(
        'articulo/update/<int:pk>',
        articulo_update,
        name='articulo-update'
    ),
    path(
        'articulo/delete/<int:pk>',
        articulo_delete,
        name='articulo-delete'
    ),

]

apps/ventas/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.seguridad.views import *
from apps.ventas.views import *
from django.contrib.auth.views import LogoutView
app_name='ventas'
urlpatterns=[
    url(r'^eliminarPendientes/', eliminarPendientes,name="eliminarPendientes"),
    url(r'^sinFinalizar/', sinFinalizar,name="sinFinalizar"),
    url(r'^iniciarVenta/', iniciarVenta,name="iniciar"),
    url(r'^vender/(?P<idPedido>\w+)', venta,name="vender"),
    url(r'^final/(?P<idPedido>\w+)', finalizarVenta,name="finalizar"),
    url(r'^cancelar/(?P<idPedido>\w+)', cancelarVenta,name="cancelar"),
    url(r'^añadir/(?P<idPedido>\w+)/(?P<idProducto>\w+)', agregarLinea,name="añadir"),
    url(r'^editar/(?P<idLinea>\w+)/', editarLinea,name="editar"),
    url(r'^eliminar/(?P<idLinea>\w+)/', eliminarLinea,name="eliminar"),
    path(
    	'empleado/', 
    	empleado_list,
    	name='empleado-list'
    ),
    path(
    	'empleado/create/',
    	empleado_create,
    	name='empleado-create'
    ),
    path(
        'empleado/update/<int:pk>',
        empleado_update,
        name='empleado-update'
    ),
    path(
        'empleado/delete/<int:pk>',
        empleado_delete,
        name='empleado-delete'
    ),

    path(
    	'meta/', 
    	meta_list,
    	name='meta-list'
    ),
    path(
    	'meta/create/',
    	meta_create,
    	name='meta-create'
    ),
    path(
        'meta/update/<int:pk>',
        meta_update,
        name='meta-update'
    ),
    path(
        'meta/delete/<int:pk>',
        meta_delete,
        name='meta-delete'
    ),
    path(
    	'asignacion/', 
    	asignacion_list,
    	name='asignacion-list'
    ),
    path(
    	'asignacion/create/',
    	asignacion_create,
    	name='asignacion-create'
    ),
    path(
        'asignacion/update/<int:pk>',
        asignacion_update,
        name='asignacion-update'
    ),
    path(
        'asignacion/delete/<int:pk>',
        asignacion_delete,
        name='asignacion-delete'
    ),

    path(
        'productos/categoria/',
        informe_productos_categoria,
        name='productos-categoria'
    ),

    #INFORMES 

    #ventas por producto
    path(
        'ventas/totales/',
        informe_ventas_totales,
        name='ventas-totales'
    ),
    path(
        'ventas/totales/pdf',
        informe_ventas_totales_pdf,
        name='ventas-totales-pdf'
    ),

    #ventas por categoria
    path(
        'informe/categoria/',
        informe_productos_categoria,
        name='informe-categoria'
    ),
    path(
        'informe/categoria/pdf',
        informe_productos_categoria_pdf,
        name='informe-categoria-pdf'
    ),

    #inventarios
    path(
        'informe/existencia/',
        informe_existencia_productos,
        name='informe-existencia'
    ),
    path(
        'informe/existencia/pdf',
        informe_existencia_productos_pdf,
        name='informe-existencia-pdf'
    ),

    #metas diarias
    path(
        'meta/diaria',
        informe_meta_diaria,
        name='empleado-meta-diaria'
    ),
    path(
        'meta/diaria/pdf',
        informe_meta_diaria_pdf,
        name='ventas-meta_diaria-pdf'
    ),
    path(
        'meta/quincenal',
        informe_meta_quincenal,
        name='empleado-meta-quincenal'
    ),
    path(
        'meta/quincenal/pdf',
        informe_meta_quincenal_pdf,
        name='ventas-meta_quincenal-pdf'
    ),
    path(
        'meta/mensual',
        informe_meta_mensual,
        name='empleado-meta-mensual'
    ),
    path(
        'meta/mensual/pdf',
        informe_meta_mensual_pdf,
        name='ventas-meta_mensual-pdf'
    ),
]

dsi115/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('seguridad/',include('apps.seguridad.urls')),
    path('inventario/',include('apps.inventario.urls')),
    path('compras/',include('apps.compras.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('', RedirectView.as_view(url='/seguridad/login', permanent=False)),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

apps/ventas/views.py
from .forms	import *
from .models import *
from apps.inventario.models import Producto, Proveedor, Categoria
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.db.models import Sum
from datetime import datetime
from django.db.models import Q
from django.db.models import Count
from django.contrib.humanize.templatetags.humanize import intcomma

import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

def eliminarPendientes(request):
    pedid=pedido.objects.filter(finalizada=False)
    if pedid.count()>0:
        pedid.delete()
    return redirect("/")

def sinFinalizar(request):
    pedidos=pedido.objects.filter(finalizada=False)
    return render(request,'ventas/venta/sinFinalizar.html',{'pedidos':pedidos})

def cancelarVenta(request,idPedido):
    pedid=pedido.objects.get(id=int(idPedido))
    print(pedid.total)
    if lineaDeVenta.objects.filter(pedidofk=pedid.id).count()>0:
        lineaDeVenta.objects.filter(pedidofk=pedid.id).delete()
    try:
        Renta.objects.get(id=pedid.renta.id).delete()
        pedid.delete()
        return redirect("/")
    except:
        pedid.delete()
        return redirect("/")

def venta(request, idPedido):
    #metodo que recupera lo mandado en la barra de buscar
    buscar=request.POST.get("buscar")
    lineas = lineaDeVenta.objects.filter(pedidofk=int(idPedido))
    pedid = pedido.objects.get(id=int(idPedido))
    error=pedid.nope
    pedid.errorContra()
    pedid.save()
    if buscar:
        #funcion que busca por nombre 
        productos=Producto.objects.filter(Q(nombre__icontains=buscar))
    else: 
      productos = Producto.objects.all()
    try:
        renta = Renta.objects.get(id=pedid.renta.id)
        return render(request,'ventas/venta/factura.html',{'pedid':pedid,'lineas':lineas, 'productos':productos,'error':error,'renta':renta})
    except:
        return render(request,'ventas/venta/factura.html',{'pedid':pedid,'lineas':lineas, 'productos':productos,'error':error})

def finalizarVenta(request,idPedido):
    ped=pedido.objects.get(id=int(idPedido))
    if request.method=='POST':
        con=contra(request.POST)
        if con.is_valid():
            datos=con.cleaned_data
            try: 
                emple=Empleado.objects.get(clave=datos.get("passwd"))
                ped.setFinal()
                lineas = lineaDeVenta.objects.filter(pedidofk=int(idPedido))
                for linea in lineas:
                    producto = Producto.objects.get(id=linea.articulofk.id)
                    producto.removerInventario(linea.cantidad)
                    producto.save()
                ped.setVendedor(emple)
                ped.setTipoPago(datos.get("typ").get())
                ped.save()
                return redirect('/')
            except:
                if ped.nope == False:
                    ped.nope=True
                    print("holi")
                    ped.save()
                return redirect('/ventas/vender/'+str(ped.id))   
    else:
        return render(request,'ventas/venta/confirmar.html',{'ped':ped,'form':contra()})

def eliminarLinea(request, idLinea):
    var=lineaDeVenta.objects.get(id=int(idLinea))
    pedid=var.pedidofk
    pedid.quitar(var.getSubtotal())
    pedid.save()
    var.delete()
    try:
        renta=Renta.objects.get(id=pedid.renta.id)
        renta.calcular(pedid.total)
        renta.totalPagar=pedid.total+renta.pagoIva            
        renta.save()
        return redirect('/ventas/vender/'+str(pedid.id))
    except:
        return redirect('/ventas/vender/'+str(pedid.id))
     
def editarLinea(request, idLinea):
    linea=lineaDeVenta.objects.get(id=int(idLinea))
    if request.method == 'POST':
        form = agregar(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            pedid=linea.pedidofk
            pedid.quitar(linea.getSubtotal())
            linea.setCantidad(form_data.get("cantidad"))
            linea.sub()
            linea.save()
            pedid.setTotal(linea.getSubtotal())
            pedid.save()
            try:
                renta=Renta.objects.get(id=pedid.renta.id)
                renta.calcular(pedid.total)           
                renta.totalPagar=pedid.total+renta.pagoIva            
                renta.save()
                return redirect('/ventas/vender/'+str(linea.pedidofk.id))
            except:
                return redirect('/ventas/vender/'+str(linea.pedidofk.id))
    else:
        form=agregar()
        content={'form':form,'linea':linea}
    return render(request,'ventas/venta/editar.html',content)

def agregarLinea(request,idPedido,idProducto):
    pedid=pedido.objects.get(id=int(idPedido))
    prod=Producto.objects.get(id=int(idProducto))
    if request.method == 'POST':
        form=agregar(request.POST)
        if form.is_valid():
            form_data=form.cleaned_data
            linea=lineaDeVenta()
            linea.setArticulo(prod)
            linea.setCantidad(int(form_data.get("cantidad")))
            linea.setPedido(pedid)
            linea.sub()
            linea.save()
            pedid.setTotal(linea.getSubtotal())
            pedid.save()
            try:
                renta=Renta.objects.get(id=pedid.renta.id)
                renta.calcular(pedid.total)    
                renta.totalPagar=pedid.total+renta.pagoIva                   
                renta.save()
                ruta='/ventas/vender/'+str(pedid.id)
                return redirect(ruta)
            except:
                ruta='/ventas/vender/'+str(pedid.id)
                return redirect(ruta)
    else:
        form=agregar()
        variables={'form':form,'pedid':pedid,'prod':prod}
        return render (request,'ventas/venta/agregar.html',variables)

def iniciarVenta(request):
    if request.method =='POST':
        form=iniciarVe(request.POST)
        if form.is_valid():            
            form_data=form.cleaned_data
            venta=pedido()
            venta.setCliente(form_data.get("cliente"))
            if(form_data.get("credito")==True):
                renta = Renta()
                renta.save()
                venta.setRenta(renta)
                venta.save()
            else:
                venta.save()
            ruta='/ventas/vender/'+str(venta.id)
            return redirect(ruta)
    else:
        form=iniciarVe()
        return render(request,'ventas/venta/iniciarVenta.html',{'form':form})



@login_required
def informe_meta_diaria(request):
    mes_actual = datetime.now().month
    anio_actual = datetime.now().year
    dia_actual = datetime.now().day

    #obtiene el total de las ventas realizadas por empledado en un tiempo especifico
    meta_diaria = Asignacion.objects.filter(tipo_meta=1)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  
    
    return render(request,'ventas/informes/empleado_meta_diaria.html',
    {'totales':totales,'meta_diaria':meta_diaria,'anio':anio_actual,'mes':mes_actual,'dia':dia_actual})

@login_required
def informe_meta_diaria_pdf(request):
    template_path = 'ventas/informes/ventas_meta_diaria_pdf.html'

    anio_actual = datetime.now().year
    meta_diaria = Asignacion.objects.filter(tipo_meta=1)
    
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  

    context = {'totales':totales,'meta_diaria':meta_diaria}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@login_required
def informe_meta_quincenal(request):
    mes_actual = datetime.now().month
    anio_actual = datetime.now().year
    dia_actual = datetime.now().day

    #obtiene el total de las ventas realizadas por empledado en un tiempo especifico
    meta_diaria = Asignacion.objects.filter(tipo_meta=2)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  
    
    return render(request,'ventas/informes/empleado_meta_quincenal.html',
    {'totales':totales,'meta_diaria':meta_diaria})

@login_required
def informe_meta_quincenal_pdf(request):
    template_path = 'ventas/informes/ventas_meta_quincenal_pdf.html'

    anio_actual = datetime.now().year
    meta_diaria = Asignacion.objects.filter(tipo_meta=2)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  

    context = {'totales':totales,'meta_diaria':meta_diaria}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)

templates/ventas/asignacion/asignacion_create.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<form method="POST" action="{% url 'ventas:asignacion-create' %}" class="js-asignacion-create-form">
	{% csrf_token %}

	<div class="modal-header">
		<h3 class="modal-title">Asignacion de Metas</h4>
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-body">
		{{ form|crispy }}
	</div>

	<div class="modal-footer">
	    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    	<button type="submit" class="btn btn-primary">Guardar</button>
	</div>
</form>

templates/ventas/asignacion/asignacion_delete.html
<form method="POST" action="{% url 'ventas:asignacion-delete' asignacion.id %}" class="js-asignacion-delete-form">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Aviso: Confirmar Eliminación</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p class="lead">¿Está seguro que desea eliminar esta asignacion? ¡LA INFORMACIÓN YA NO PODRÁ RECUPERARSE!</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      <button type="submit" class="btn btn-danger">Eliminar</button>
    </div>
  </form>

templates/ventas/asignacion/asignacion_list.html
{% extends 'base/base_sistema.html' %}
{% load static %} 
{% block title %}SIAVAC | Asigaciones{% endblock %}
{% block titulo_contenido %}Asignación de Metas{% endblock titulo_contenido%}
{% block previa_contenido %}Lleve un control de ventas por cada vendedor para establecer incentivos.{% endblock previa_contenido%}
{% block inf %}
Edite la asignación de un empleado en específico dando click en <img src="/static/images/editar.png" title="Editar" width="20" height="20"/> o elimine un registro de la tabla en <img src="/static/images/delete.png" title="Eliminar" width="20" height="20"/>. Puede ver el porcentaje de avance del trabajador con respecto a la meta asignada y sus resultados en <strong>Ver Informe de Ventas</strong> 
{% endblock inf%}
{% block bsq %}
  <p style="text-align:center">
    <button type="button" class="btn btn-primary js-create-asignacion" data-url="{% url 'ventas:asignacion-create' %}">
      <span class="glyphicon glyphicon-plus"></span>Agregar nueva Asignación
    </button> 
  </p>

  <div style="text-align:center" class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Informe de Metas
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a href="{% url 'ventas:empleado-meta-diaria' %}" class="dropdown-item" href="#">Diarias</a>
      <a href="{% url 'ventas:empleado-meta-quincenal' %}" class="dropdown-item" href="#">Quincenales</a>
      <a href="{% url 'ventas:empleado-meta-mensual' %}" class="dropdown-item" href="#">Mensuales</a>
    </div>
  </div>


  Para regresar a la pantalla principal de ventas, haga click en:
  <p style="text-align:center"><a href="{% url 'compras:index' %}">
      <button type="button" class="btn btn-primary js-create-empleado">Regresar a Ventas</button>
    </a></p> 
{% endblock bsq%}
{% block javascript %}
  <script src="{% static 'js/asignaciones.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
  
  <table class="table" id="asignacion-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Empleado</th>
        <th>Meta Asignada</th>
        <th>Tipo de Meta</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
     {% include 'ventas/asignacion/asignacion_list_2.html' %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-asignacion">
    <div class="modal-dialog">
      <div class="modal-content">
        
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/ventas/asignacion/asignacion_list_2.html
{% for asignacion in asignaciones %}
<tr>
    <td>{{forloop.counter}}</td>
    <td>{{ asignacion.empleadofk }} {{ asignacion.empleadofk.apellidos }}</td>
    <td>{{ asignacion.meta_asignadafk }}</td>
    {% if asignacion.tipo_meta == 1 %}
    <td>Diaria</td>
    {% elif asignacion.tipo_meta == 2 %}
    <td>Quincenal</td>
    {% elif asignacion.tipo_meta == 3 %}
    <td>Mensual</td>
    {% endif %}


    <td>

        <button type="button"
            class="btn btn-warning btn-sm js-update-asignacion"
            data-url="{% url 'ventas:asignacion-update' asignacion.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
            <img src="/static/images/editar.png" title="Editar" width="20" height="20"/>
         </button>
        <button type="button"
          class="btn btn-danger btn-sm js-delete-asignacion"
          data-url="{% url 'ventas:asignacion-delete' asignacion.id %}">
            <span class="glyphicon glyphicon-trash"></span>
             <img src="/static/images/delete.png" title="Editar" width="20" height="20"/>
          </button>
    </td>
{% empty %}
<tr>
      <td colspan="8" class="text-center bg-warning">No hay asignaciones realizadas</td>
</tr>
{% endfor %}

templates/ventas/asignacion/asignacion_update.html
{% load crispy_forms_tags %}

<form method="POST" action="{% url 'ventas:asignacion-update' form.instance.pk %}" class="js-asignacion-update-form">
  {% csrf_token %}
  <div class="modal-header">
    
    <h4 class="modal-title">Actualizar Datos de la Asignacion</h4>
  </div>
  <div class="modal-body">
    {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary">Actualizar</button>
  </div>
</form>