apps/compras/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.compras.views import *

app_name='compras'
urlpatterns=[
    url(r'^cancel/(?P<idPedido>\w+)',cancelarPedido,name="cancel"),
    url(r'^aceptar/(?P<idPedido>\w+)',recibirPedido,name="aceptar"),
    url(r'^index',verpedidos,name="index"),
    url(r'^realizarCompras',agregarPedido,name="reCom"),
    url(r'^add/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', agregarLinea,name="add"),
    url(r'^editar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', editarLinea,name="editarLinea"),
    url(r'^borrar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', borrarLinea,name="borrarLinea"),
    #url(r'^addPedido', agregarPedido, name="addP"),
    url(r'^pedir/(?P<idPedido>\w+)/(?P<idProveedor>\w+)/', lineapedido, name="lin"),
    url(r'^cancelar/(?P<idPedido>\w+)/', cancelar, name="cancelar"),
    url(r'^verDetalle/(?P<idPedido>\w+)/', verDetalle, name="verDetalle"),
    url(r'^gestionarPedidos',PedidosList,name="gesPed"),
    
    path(
    	'proveedor/', 
    	proveedor_list,
    	name='proveedor-list'
    ),
    path(
    	'proveedor/create/',
    	proveedor_create,
    	name='proveedor-create'
    ),
    path(
        'proveedor/update/<int:pk>',
        proveedor_update,
        name='proveedor-update'
    ),
    path(
        'proveedor/delete/<int:pk>',
        proveedor_delete,
        name='proveedor-delete'
    ),


    path(
    	'articulo/', 
    	articulo_list,
    	name='articulo-list'
    ),
    path(
    	'articulo/create/',
    	articulo_create,
    	name='articulo-create'
    ),
    path(
        'articulo/update/<int:pk>',
        articulo_update,
        name='articulo-update'
    ),
    path(
        'articulo/delete/<int:pk>',
        articulo_delete,
        name='articulo-delete'
    ),

]

apps/inventario/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from apps.inventario.views import *
app_name='inventario'
urlpatterns=[
url(r'^inventario', inventario ,name="inventario"),
url(r'^consulta',consulta,name="consulta"),	
url(r'^notificaciones',notificaciones,name="notif"),
url(r'^cuentas',cuentas,name="cuent"),
url(r'^editar_producto/(?P<idProducto>\w+)', gestprod2, name="gestprod"),
url(r'^eliminar_producto/(?P<idProducto>\w+)',deleteprod, name="elimprod"),
url(r'^editar_cuenta/(?P<idCuenta>\w+)', gestcuent, name="gestcuent"),
url(r'^eliminar_cuenta/(?P<idCuenta>\w+)',deletecuent, name="elimcuent"),
url(r'^addcuenta/', addcuenta, name="addcuent"),
]

apps/seguridad/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from apps.seguridad.views import *
from django.contrib.auth.views import LogoutView
app_name='seguridad'
urlpatterns=[
url(r'^index', index, name="index"),
url(r'^login', auth, name="ingresar"),
url(r'^logout', LogoutView.as_view(next_page='seguridad:ingresar'), name="logout"),
]

apps/ventas/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.seguridad.views import *
from apps.ventas.views import *
from django.contrib.auth.views import LogoutView
app_name='ventas'
urlpatterns=[
    url(r'^eliminarPendientes/', eliminarPendientes,name="eliminarPendientes"),
    url(r'^sinFinalizar/', sinFinalizar,name="sinFinalizar"),
    url(r'^iniciarVenta/', iniciarVenta,name="iniciar"),
    url(r'^vender/(?P<idPedido>\w+)', venta,name="vender"),
    url(r'^final/(?P<idPedido>\w+)', finalizarVenta,name="finalizar"),
    url(r'^cancelar/(?P<idPedido>\w+)', cancelarVenta,name="cancelar"),
    url(r'^añadir/(?P<idPedido>\w+)/(?P<idProducto>\w+)', agregarLinea,name="añadir"),
    url(r'^editar/(?P<idLinea>\w+)/', editarLinea,name="editar"),
    url(r'^eliminar/(?P<idLinea>\w+)/', eliminarLinea,name="eliminar"),
    path(
    	'empleado/', 
    	empleado_list,
    	name='empleado-list'
    ),
    path(
    	'empleado/create/',
    	empleado_create,
    	name='empleado-create'
    ),
    path(
        'empleado/update/<int:pk>',
        empleado_update,
        name='empleado-update'
    ),
    path(
        'empleado/delete/<int:pk>',
        empleado_delete,
        name='empleado-delete'
    ),

    path(
    	'meta/', 
    	meta_list,
    	name='meta-list'
    ),
    path(
    	'meta/create/',
    	meta_create,
    	name='meta-create'
    ),
    path(
        'meta/update/<int:pk>',
        meta_update,
        name='meta-update'
    ),
    path(
        'meta/delete/<int:pk>',
        meta_delete,
        name='meta-delete'
    ),
    path(
    	'asignacion/', 
    	asignacion_list,
    	name='asignacion-list'
    ),
    path(
    	'asignacion/create/',
    	asignacion_create,
    	name='asignacion-create'
    ),
    path(
        'asignacion/update/<int:pk>',
        asignacion_update,
        name='asignacion-update'
    ),
    path(
        'asignacion/delete/<int:pk>',
        asignacion_delete,
        name='asignacion-delete'
    ),

    path(
        'productos/categoria/',
        informe_productos_categoria,
        name='productos-categoria'
    ),

    #INFORMES 

    #ventas por producto
    path(
        'ventas/totales/',
        informe_ventas_totales,
        name='ventas-totales'
    ),
    path(
        'ventas/totales/pdf',
        informe_ventas_totales_pdf,
        name='ventas-totales-pdf'
    ),

    #ventas por categoria
    path(
        'informe/categoria/',
        informe_productos_categoria,
        name='informe-categoria'
    ),
    path(
        'informe/categoria/pdf',
        informe_productos_categoria_pdf,
        name='informe-categoria-pdf'
    ),

    #inventarios
    path(
        'informe/existencia/',
        informe_existencia_productos,
        name='informe-existencia'
    ),
    path(
        'informe/existencia/pdf',
        informe_existencia_productos_pdf,
        name='informe-existencia-pdf'
    ),

    #metas diarias
    path(
        'meta/diaria',
        informe_meta_diaria,
        name='empleado-meta-diaria'
    ),
    path(
        'meta/diaria/pdf',
        informe_meta_diaria_pdf,
        name='ventas-meta_diaria-pdf'
    ),
    path(
        'meta/quincenal',
        informe_meta_quincenal,
        name='empleado-meta-quincenal'
    ),
    path(
        'meta/quincenal/pdf',
        informe_meta_quincenal_pdf,
        name='ventas-meta_quincenal-pdf'
    ),
    path(
        'meta/mensual',
        informe_meta_mensual,
        name='empleado-meta-mensual'
    ),
    path(
        'meta/mensual/pdf',
        informe_meta_mensual_pdf,
        name='ventas-meta_mensual-pdf'
    ),
]

dsi115/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('seguridad/',include('apps.seguridad.urls')),
    path('inventario/',include('apps.inventario.urls')),
    path('compras/',include('apps.compras.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('', RedirectView.as_view(url='/seguridad/login', permanent=False)),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/base/add_proveedor.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Agregar Proveedor{% endblock %}
{% block content %}
    
<h1><br>Agregar Nuevo Proveedor</h1>

    <table class="bordered">
        <tr><td>Nombre del nuevo proveedor:</td><td><input type="text"></td></tr>
        <tr><td>Teléfono:</td><td><input type="text"></td></tr>
        <tr><td>Dirección:</td><td><input type="text"></td></tr>
    </table>
<br>
<table style="margin: 0 auto;">
    <tr><td><button type="submit" class="boton">Guardar</button></td><td>&nbsp;&nbsp;</td>
            <td><button type="submit" class="boton">Cancelar</button></td></tr>
</table>
        {% endblock %}

templates/base/b_login.html
{% load static %}
<!DOCTYPE html>

<header id="header">
		<title>SIAVAC</title>
			<link rel="stylesheet" href="{% static 'css/cssB.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
            <link rel="stylesheet" href="{% static 'css/cssF.css' %}">
            <link rel="stylesheet" href="{% static 'css/cssG.css' %}">
            <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
            <script type="text/javascript" src="/static/js/jquery.min.1.9.js"></script>
            <script type="text/javascript" src="/static/js/jquery.min.js"></script>
            <script type="text/javascript" src="/static/js/script1.js"></script>
            <link rel="stylesheet" type="text/css" href="/static/css/ABCwin2.css"/>
            <script type="text/javascript" src="/static/js/ABCwin2.js"></script>

    <div class="container">
      <div class="logo float-left">
        <h1 class="text-light"><a href="/" class="scrollto"><span>SIAVAC</span></a></h1>
      </div>
     
    </div>
  </header><!-- #header -->
<body>
	<section id="about">

      <div class="d-flex justify-content-center">

        <div class="row">
          <div class="col-12">
            <div class="about-content">
              <h2>{% block titulo_contenido %}{% endblock titulo_contenido%}</h2>
              
            </div>
          </div>
          <div class="row">
                    <div class="col-8">
                      <div class="about-content">
                        <p>{% block inf %}{% endblock inf%}</p>
                          {% block bsq %}
              {% endblock bsq%}
                      </div>
                    </div>

                    <div class="col-4">
                      <div class="about-content">
                        {% block content %}{% endblock content%}
                      </div>
                    </div>
                  </div>
        </div>

        
      </div>

    </section>
{%block propio%}
{%endblock propio%}
		
	
	<script src="{% static 'js/jquery-3.4.1.min.js' %}" ></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block javascript %}
	{% endblock javascript %}
</body>
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        Proyecto <strong>SIAVAC</strong> | Sistema Informático para la Administración y Venta de Accesorios
      </div>
      <div class="credits">
        Diseño de Sistemas II - 2020
      </div>
    </div>
  </footer>

</html>

templates/base/b_sistema.html
{% load static %}
<!DOCTYPE html>

<header id="header">
		<title>{% block title %}{% endblock %}</title>
			<link rel="stylesheet" href="{% static 'css/cssB.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
            <link rel="stylesheet" href="{% static 'css/cssF.css' %}">
            <link rel="stylesheet" href="{% static 'css/cssG.css' %}">
            <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
            <script type="text/javascript" src="/static/js/jquery.min.1.9.js"></script>
            <script type="text/javascript" src="/static/js/jquery.min.js"></script>
            <script type="text/javascript" src="/static/js/script1.js"></script>
            <link rel="stylesheet" type="text/css" href="/static/css/ABCwin2.css"/>
            <script type="text/javascript" src="/static/js/ABCwin2.js"></script>

    <div class="container">
      <div class="logo float-left">
        <h1 class="text-light"><a href="/" class="scrollto"><span>SIAVAC</span></a></h1>
      </div>
      {%block navegacion%}
      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          {%block encabezado%}
				  <li><a href="{% url 'inventario:inventario' %}">Inventario</a></li>
				  <li><a href="{% url 'compras:index' %}">Compras</a></li>
          <li><a href="{% url 'inventario:notif'  %}" rel="get:id=10" rev="abcwin[500,auto]">Notificaciones</a></li>
          <li class="drop-down"><a href="">Recursos Humanos</a>
              <ul>
                  <li><a href="{% url 'ventas:empleado-list'  %}">Empleados</a></li>
                  <li><a href="{% url 'ventas:meta-list' %}">Gestión de Metas</a></li>
                  <li><a href="{% url 'ventas:asignacion-list' %}">Asignación de Metas</a></li>
                </ul>
          </li>
          <li><a href=""></a>
            <ul></ul>
            <ul></ul>
            <ul></ul>
          </li>
          <div style="text-align:center" class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Informe de Metas
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a href="{% url 'ventas:empleado-meta-diaria' %}" class="dropdown-item" href="#">Diarias</a>
              <a href="{% url 'ventas:empleado-meta-quincenal' %}" class="dropdown-item" href="#">Quincenales</a>
              <a href="{% url 'ventas:empleado-meta-mensual' %}" class="dropdown-item" href="#">Mensuales</a>
            </div>
          </div>
        {%endblock encabezado%}
				<li style="float:right" class="salir"><a href="{%  url "seguridad:logout" %}">Cerrar Sesión</a></li>
        </ul>
      </nav><!-- .main-nav -->
      {%endblock navegacion%}
    </div>
  </header><!-- #header -->
<body>
	<section id="about">

      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="about-content">
            {%block propio%}
{%endblock propio%}
            </div>
          </div>
        </div>
      </div>

    </section>

		
	
	<script src="{% static 'js/jquery-3.4.1.min.js' %}" ></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block javascript %}
	{% endblock javascript %}
</body>
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        Proyecto <strong>SIAVAC</strong> | Sistema Informático para la Administración y Venta de Accesorios
      </div>
      <div class="credits">
        Diseño de Sistemas II - 2020
      </div>
    </div>
  </footer>

</html>

templates/base/base_sistema.html
{% load static %}
<!DOCTYPE html>

<header id="header">
		<title>{% block title %}{% endblock %}</title>
			<link rel="stylesheet" href="{% static 'css/cssB.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
            <link rel="stylesheet" href="{% static 'css/cssF.css' %}">
            <link rel="stylesheet" href="{% static 'css/cssG.css' %}">
            <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
            <script type="text/javascript" src="/static/js/jquery.min.1.9.js"></script>
            <script type="text/javascript" src="/static/js/jquery.min.js"></script>
            <script type="text/javascript" src="/static/js/script1.js"></script>
            <link rel="stylesheet" type="text/css" href="/static/css/ABCwin2.css"/>
             <script src="{% static 'js/articulos.js' %}"></script>
            <script type="text/javascript" src="/static/js/ABCwin2.js"></script>
         


    <div class="container">
      <div class="logo float-left">
        <h1 class="text-light"><a href="/seguridad/index" class="scrollto"><span>SIAVAC</span></a></h1>
      </div>
      {%block navegacion%}
      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          {%block encabezado%}
				  <li><a href="{% url 'inventario:inventario' %}">Inventario</a></li>
				  <li><a href="{% url 'compras:index' %}">Compras</a></li>
            <li><a href="{% url 'inventario:cuent' %}">Cuentas</a></li>
          <li><a href="{% url 'inventario:notif'  %}" rel="get:id=10" rev="abcwin[500,auto]">Notificaciones</a></li>
          <li class="drop-down"><a href="">Recursos Humanos</a>
              <ul>
                  <li><a href="{% url 'ventas:empleado-list'  %}">Empleados</a></li>
                  <li><a href="{% url 'ventas:meta-list' %}">Gestión de Metas</a></li>
                  <li><a href="{% url 'ventas:asignacion-list' %}">Asignación de Metas</a></li>
                </ul>
          </li>
          <li class="drop-down"><a href="">Informes</a>
            <ul>
              <li class="drop-down"><a>De Metas</a>
                <ul>
                  <li><a href="{% url 'ventas:empleado-meta-diaria' %}" class="dropdown-item">Diarias</a></li>
                  <li><a href="{% url 'ventas:empleado-meta-quincenal' %}" class="dropdown-item">Quincenales</a></li>
                  <li><a href="{% url 'ventas:empleado-meta-mensual' %}" class="dropdown-item">Mensuales</a></li>
                </ul>
  
              <li class="drop-down"><a>De Ventas</a>
                <ul>
                  <li ><a href="{% url 'ventas:ventas-totales' %}" class="dropdown-item">Por Producto</a></li>
                  <li ><a href="{% url 'ventas:informe-categoria' %}" class="dropdown-item">Por Categoria</a></li>
                </ul>
                <li class="drop-down"><a href="{% url 'ventas:informe-existencia' %}" class="dropdown-item">Inventario</a></li>
            </ul>

          </li>
          
        {%endblock encabezado%}
				<li style="float:right" class="salir"><a href="{%  url "seguridad:logout" %}">Cerrar Sesión</a></li>
        </ul>
      </nav><!-- .main-nav -->
      {%endblock navegacion%}
    </div>
  </header><!-- #header -->
<body>
	<section id="about">

      <div class="container">
        <div class="row">

          <div class="col-4">
            <div class="about-content">
              <h2>{% block titulo_contenido %}{% endblock titulo_contenido%}</h2>
              <h3>{% block previa_contenido %}{% endblock previa_contenido%}</h3>
              <p>{% block inf %}{% endblock inf%}</p>
                {% block bsq %}
		{% endblock bsq%}
            </div>
          </div>

          <div class="col-8">
            <div class="about-content">
              {% block content %}{% endblock content%}
            </div>
          </div>
        </div>
      </div>

    </section>
{%block propio%}
{%endblock propio%}
		
	
	<script src="{% static 'js/jquery-3.4.1.min.js' %}" ></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block javascript %}
	{% endblock javascript %}
</body>
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        Proyecto <strong>SIAVAC</strong> | Sistema Informático para la Administración y Venta de Accesorios
      </div>
      <div class="credits">
        Diseño de Sistemas II - 2020
      </div>
    </div>
  </footer>

</html>

templates/base/existencias.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Existencias{% endblock %}
{% block titulo_contenido %}Existencias{% endblock titulo_contenido%}
{% block previa_contenido %}Se presentan los productos registrados con las opciones para editar y eliminar.{% endblock previa_contenido%}
{% block inf %}


Edite la información registrada de un artículo en existencia seleccionando el ícono <img src="/static/images/editar.png" title="Editar" width="20" height="20"/> al lado del producto que desea modificar. Elimine un elemento de la tabla haciendo click en <img src="/static/images/delete.png" title="Eliminar" width="20" height="20"/>. <p>Realice la búsqueda de un artículo en específico ingresando el nombre del producto:</p>
{% endblock inf%}



{% block bsq %}
<style type="text/css"> 
  input[type=text] {
  width: 150px;
  }
</style>
      <form method="post"> 
      {% csrf_token %} 
       <input type="text" placeholder="Buscar Producto" name="buscar" value="{{request.GET.buscar }}"> 
       <button type="submit" class="btn btn-primary btn-primary">Buscar</button>
       <button type="submit" class="btn btn-primary btn-primary" onclick="location.reload();">Actualizar</button>  

      </form> 
       <p>
    <button type="button" class="btn btn-primary js-create-articulo"
          data-url="{% url 'compras:articulo-create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      Nuevo Articulo
    </button>
  </p>  
  
  <div class="modal fade" id="modal-articulo">
    <div class="modal-dialog">
      <div class="modal-content">
        
      </div>
    </div>
  </div>
{% endblock bsq%}
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/css/ABCwin.css"/>
  <script type="text/javascript" src="/static/js/ABCwin.js"></script>
     {% if messages %} 
    <ul class="messages"> 
       {% for message in messages%} 
        <div class="alert alert-{{ message.tags }}" role="alert"> 
          <p>{{ message }}</p> 
      </div> 
       {% endfor %} 
    </ul> 
    {% endif %} 
    <table class="table" id="proveedor-table">
    <thead>
    <tr><th>Nombre</th><th>Descripción</th><th>Precio de compra</th><th>Precio de venta</th> <th>Existencias</th><th>Acciones</th></tr>
	</thead>
	<tbody>
   {% for producto in productos%}
   
   <tr>
   	<td>{{producto.nombre}}</td>
   	<td>{{producto.descripcion}}</td>
   	<td>{{producto.preciocompra}}</td>
   	<td>{{producto.precioventa}}</td>
   	 {% if producto.existencia <= producto.minimo %}
     <td bgcolor="red">{{producto.existencia}}</td>
    {% else %}
     <td>{{producto.existencia}}</td>
    {% endif %}
    <td></td>
<td><a href="{% url 'inventario:gestprod' producto.id %}" rel="get:id=10" rev="abcwin[500,auto]"><img src="/static/images/editar.png" title="Editar" width="20" height="20"/></a>
       <a href="{% url 'inventario:elimprod' producto.id %}" rel="get:id=10" rev="abcwin[500,auto]"><img src="/static/images/delete.png" title="Eliminar" width="20" height="20"/></a></td>
   </tr>
   {%endfor%}
    </tbody>
</table>
        {% endblock %}


templates/base/existencias2.html
{% block bsq %}
<style type="text/css"> 
  input[type=text] {
  width: 150px;
  }
</style>
      <form method="post"> 
      {% csrf_token %} 
       <input type="text" placeholder="Buscar Producto" name="buscar" value="{{request.GET.buscar }}"> 
       <button type="submit" class="btn btn-primary btn-primary">Buscar</button>
       <button type="submit" class="btn btn-primary btn-primary" onclick="location.reload();">Actualizar</button>  

      </form> 
       <p>
    <button type="button" class="btn btn-primary js-create-articulo"
          data-url="{% url 'compras:articulo-create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      Nuevo Articulo
    </button>
  </p>  
  
  <div class="modal fade" id="modal-articulo">
    <div class="modal-dialog">
      <div class="modal-content">
        
      </div>
    </div>
  </div>
{% endblock bsq%}
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/css/ABCwin.css"/>
  <script type="text/javascript" src="/static/js/ABCwin.js"></script>
     {% if messages %} 
    <ul class="messages"> 
       {% for message in messages%} 
        <div class="alert alert-{{ message.tags }}" role="alert"> 
          <p>{{ message }}</p> 
      </div> 
       {% endfor %} 
    </ul> 
    {% endif %} 
    <table class="table" id="proveedor-table">
    <thead>
    <tr><th>Nombre</th><th>Descripción</th><th>Precio de compra</th><th>Precio de venta</th> <th>Existencias</th><th>Acciones</th></tr>
	</thead>
	<tbody>
   {% for producto in productos%}
   <tr>
   	<td>{{producto.nombre}}</td>
   	<td>{{producto.descripcion}}</td>
   	<td>{{producto.preciocompra}}</td>
   	<td>{{producto.precioventa}}</td>
   	 {% if producto.existencia <= producto.minimo %}
     <td bgcolor="red">{{producto.existencia}}</td>
    {% else %}
     <td>{{producto.existencia}}</td>
    {% endif %}
<td><a href="{% url 'inventario:gestprod' producto.id %}" rel="get:id=10" rev="abcwin[500,auto]"><img src="/static/images/editar.png" title="Editar" width="20" height="20"/></a>
       <a href="{% url 'inventario:elimprod' producto.id %}" rel="get:id=10" rev="abcwin[500,auto]"><img src="/static/images/delete.png" title="Eliminar" width="20" height="20"/></a></td>
   </tr>
   {%endfor%}
    </tbody>
</table>
        {% endblock %}

templates/base/proveedores.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Proveedores{% endblock %}
{% block content %}
<h1>Proveedores</h1>
    <table class="bordered">
    <thead>

    <tr>
        <th>Código</th>        
        <th>Nombre del Proveedor</th>
        <th>Teléfono</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>0001</td>        
        <td>Accesorios y más S.A</td>
        <td>0000-0000</td>
        <td><a href="">Editar</a></td>
    </tr>        
    <tr>
        <td>0002</td>         
        <td>Autos V</td>
        <td>0000-0000</td>
        <td><a href="">Editar</a></td>
    </tr>
    <tr>

        <td>0003</td>         
        <td>Autos y Motos S.A</td>
        <td>0000-0000</td>
        <td><a href="">Editar</a></td>
    </tr>    
    <tr>
        <td>0004</td> 
        <td>Accesorios y Repuestos</td>
        <td>0000-0000</td>
        <td><a href="">Editar</a></td>

    </tr>
    <tr>
        <td>0005</td> 
        <td>Baterías 1</td>
        <td>0000-0000</td>
        <td><a href="">Editar</a></td>
    </tr>
    </tbody>
</table>
<table style="margin: 0 auto;">
    <tr><td colspan="4"><br><button type="submit" class="boton">Agregar Nuevo Proveedor</button></td></tr>
</table>
        {% endblock %}
	