apps/ventas/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.seguridad.views import *
from apps.ventas.views import *
from django.contrib.auth.views import LogoutView
app_name='ventas'
urlpatterns=[
    url(r'^eliminarPendientes/', eliminarPendientes,name="eliminarPendientes"),
    url(r'^sinFinalizar/', sinFinalizar,name="sinFinalizar"),
    url(r'^iniciarVenta/', iniciarVenta,name="iniciar"),
    url(r'^vender/(?P<idPedido>\w+)', venta,name="vender"),
    url(r'^final/(?P<idPedido>\w+)', finalizarVenta,name="finalizar"),
    url(r'^cancelar/(?P<idPedido>\w+)', cancelarVenta,name="cancelar"),
    url(r'^añadir/(?P<idPedido>\w+)/(?P<idProducto>\w+)', agregarLinea,name="añadir"),
    url(r'^editar/(?P<idLinea>\w+)/', editarLinea,name="editar"),
    url(r'^eliminar/(?P<idLinea>\w+)/', eliminarLinea,name="eliminar"),
    path(
    	'empleado/', 
    	empleado_list,
    	name='empleado-list'
    ),
    path(
    	'empleado/create/',
    	empleado_create,
    	name='empleado-create'
    ),
    path(
        'empleado/update/<int:pk>',
        empleado_update,
        name='empleado-update'
    ),
    path(
        'empleado/delete/<int:pk>',
        empleado_delete,
        name='empleado-delete'
    ),

    path(
    	'meta/', 
    	meta_list,
    	name='meta-list'
    ),
    path(
    	'meta/create/',
    	meta_create,
    	name='meta-create'
    ),
    path(
        'meta/update/<int:pk>',
        meta_update,
        name='meta-update'
    ),
    path(
        'meta/delete/<int:pk>',
        meta_delete,
        name='meta-delete'
    ),
    path(
    	'asignacion/', 
    	asignacion_list,
    	name='asignacion-list'
    ),
    path(
    	'asignacion/create/',
    	asignacion_create,
    	name='asignacion-create'
    ),
    path(
        'asignacion/update/<int:pk>',
        asignacion_update,
        name='asignacion-update'
    ),
    path(
        'asignacion/delete/<int:pk>',
        asignacion_delete,
        name='asignacion-delete'
    ),

    path(
        'productos/categoria/',
        informe_productos_categoria,
        name='productos-categoria'
    ),

    #INFORMES 

    #ventas por producto
    path(
        'ventas/totales/',
        informe_ventas_totales,
        name='ventas-totales'
    ),
    path(
        'ventas/totales/pdf',
        informe_ventas_totales_pdf,
        name='ventas-totales-pdf'
    ),

    #ventas por categoria
    path(
        'informe/categoria/',
        informe_productos_categoria,
        name='informe-categoria'
    ),
    path(
        'informe/categoria/pdf',
        informe_productos_categoria_pdf,
        name='informe-categoria-pdf'
    ),

    #inventarios
    path(
        'informe/existencia/',
        informe_existencia_productos,
        name='informe-existencia'
    ),
    path(
        'informe/existencia/pdf',
        informe_existencia_productos_pdf,
        name='informe-existencia-pdf'
    ),

    #metas diarias
    path(
        'meta/diaria',
        informe_meta_diaria,
        name='empleado-meta-diaria'
    ),
    path(
        'meta/diaria/pdf',
        informe_meta_diaria_pdf,
        name='ventas-meta_diaria-pdf'
    ),
    path(
        'meta/quincenal',
        informe_meta_quincenal,
        name='empleado-meta-quincenal'
    ),
    path(
        'meta/quincenal/pdf',
        informe_meta_quincenal_pdf,
        name='ventas-meta_quincenal-pdf'
    ),
    path(
        'meta/mensual',
        informe_meta_mensual,
        name='empleado-meta-mensual'
    ),
    path(
        'meta/mensual/pdf',
        informe_meta_mensual_pdf,
        name='ventas-meta_mensual-pdf'
    ),
]

dsi115/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('seguridad/',include('apps.seguridad.urls')),
    path('inventario/',include('apps.inventario.urls')),
    path('compras/',include('apps.compras.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('', RedirectView.as_view(url='/seguridad/login', permanent=False)),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

apps/ventas/forms.py
from django import forms 
from django.forms import widgets
from apps.ventas.models import *
from apps.compras.models import Tipo_Pago
from django.conf import settings

tipos=Tipo_Pago.objects.all()

class EmpleadoForm(forms.ModelForm):
	class Meta:
		model = Empleado
		fields = [
			'clave', 
			'nombres', 
			'apellidos', 
			'telefono', 
			'dui',
			'nit',
		]
		labels={
			'clave':'Clave del Empleado',
			'nombres':'Nombres del Empleado',
			'apellidos':'Apellidos del Empleado',
			'telefono':'# Telefonico',
			'dui':'DUI',
			'nit':'NIT',
		}
		widgets={
			'clave' : forms.NumberInput(attrs={
				'class':'form-control',
				'placeholder':'Introduzca la clave del nuevo empleado', 
			}),
			'nombres' : forms.TextInput(attrs={'class':'form-control'}),
			'apellidos' : forms.TextInput(attrs={'class':'form-control'}),
			'telefono' : forms.NumberInput(attrs={
				'class':'form-control',
				'placeholder':'Introduzca numero telefonico', 
			}),
			'dui' : forms.TextInput(attrs={
				'class':'form-control',
				'placeholder':'Introduzca el DUI del nuevo empleado', 
			}),
			'nit' : forms.NumberInput(attrs={
				'class':'form-control',
				'placeholder':'Introduzca el NIT del nuevo empleado', 
				#'help_texts':'Ingrese el NIT completo',
			}),
		}

class MetaForm(forms.ModelForm):
	class Meta:
		model = Metas
		fields = [
			'monto_asignado', 
			'descripcion', 
		]
		labels={
			'monto_asignado':'Ingrese el monto en $',
			'descripcion':'Descripcion de la meta',
		}
		widgets={
			'monto_asignado' : forms.NumberInput(attrs={'class':'form-control'}),
			'descripcion' : forms.TextInput(attrs={'class':'form-control'}),
		}

class AsignacionForm(forms.ModelForm):
	class Meta:
		model = Asignacion
		fields = [
			'empleadofk',
			'meta_asignadafk',  
			'tipo_meta',
		]
		labels={
			'empleadofk':'Seleccione el empleado',
			'meta_asignadafk':'Asigne una meta',
			'tipo_meta':'Seleccione el tipo de meta',
		}
		widgets={
			'empleadofk' : forms.Select(attrs={'class':'form-control'}),
			'meta_asignadafk' : forms.Select(attrs={'class':'form-control'}),
			'tipo_meta': forms.Select(attrs={'class':'form-control'}),
		}

class iniciarVe(forms.Form):
	credito = forms.BooleanField(label="Necesitará crédito fiscal?",required=False)
	cliente = forms.CharField(label='Nombre del cliente',required=True,max_length=25)

class agregar(forms.Form):
	cantidad=forms.IntegerField(label="Cantidad de productos", required=True, min_value=1)

class contra(forms.Form):
	typ = forms.ModelMultipleChoiceField(tipos,required=True, label='Selecciones el método de pago')
	passwd = forms.CharField(widget=forms.PasswordInput, required=True,min_length=4,max_length=4)

apps/ventas/views.py
from .forms	import *
from .models import *
from apps.inventario.models import Producto, Proveedor, Categoria
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.db.models import Sum
from datetime import datetime
from django.db.models import Q
from django.db.models import Count
from django.contrib.humanize.templatetags.humanize import intcomma

import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

def eliminarPendientes(request):
    pedid=pedido.objects.filter(finalizada=False)
    if pedid.count()>0:
        pedid.delete()
    return redirect("/")

def sinFinalizar(request):
    pedidos=pedido.objects.filter(finalizada=False)
    return render(request,'ventas/venta/sinFinalizar.html',{'pedidos':pedidos})

def cancelarVenta(request,idPedido):
    pedid=pedido.objects.get(id=int(idPedido))
    print(pedid.total)
    if lineaDeVenta.objects.filter(pedidofk=pedid.id).count()>0:
        lineaDeVenta.objects.filter(pedidofk=pedid.id).delete()
    try:
        Renta.objects.get(id=pedid.renta.id).delete()
        pedid.delete()
        return redirect("/")
    except:
        pedid.delete()
        return redirect("/")

def venta(request, idPedido):
    #metodo que recupera lo mandado en la barra de buscar
    buscar=request.POST.get("buscar")
    lineas = lineaDeVenta.objects.filter(pedidofk=int(idPedido))
    pedid = pedido.objects.get(id=int(idPedido))
    error=pedid.nope
    pedid.errorContra()
    pedid.save()
    if buscar:
        #funcion que busca por nombre 
        productos=Producto.objects.filter(Q(nombre__icontains=buscar))
    else: 
      productos = Producto.objects.all()
    try:
        renta = Renta.objects.get(id=pedid.renta.id)
        return render(request,'ventas/venta/factura.html',{'pedid':pedid,'lineas':lineas, 'productos':productos,'error':error,'renta':renta})
    except:
        return render(request,'ventas/venta/factura.html',{'pedid':pedid,'lineas':lineas, 'productos':productos,'error':error})

def finalizarVenta(request,idPedido):
    ped=pedido.objects.get(id=int(idPedido))
    if request.method=='POST':
        con=contra(request.POST)
        if con.is_valid():
            datos=con.cleaned_data
            try: 
                emple=Empleado.objects.get(clave=datos.get("passwd"))
                ped.setFinal()
                lineas = lineaDeVenta.objects.filter(pedidofk=int(idPedido))
                for linea in lineas:
                    producto = Producto.objects.get(id=linea.articulofk.id)
                    producto.removerInventario(linea.cantidad)
                    producto.save()
                ped.setVendedor(emple)
                ped.setTipoPago(datos.get("typ").get())
                ped.save()
                return redirect('/')
            except:
                if ped.nope == False:
                    ped.nope=True
                    print("holi")
                    ped.save()
                return redirect('/ventas/vender/'+str(ped.id))   
    else:
        return render(request,'ventas/venta/confirmar.html',{'ped':ped,'form':contra()})

def eliminarLinea(request, idLinea):
    var=lineaDeVenta.objects.get(id=int(idLinea))
    pedid=var.pedidofk
    pedid.quitar(var.getSubtotal())
    pedid.save()
    var.delete()
    try:
        renta=Renta.objects.get(id=pedid.renta.id)
        renta.calcular(pedid.total)
        renta.totalPagar=pedid.total+renta.pagoIva            
        renta.save()
        return redirect('/ventas/vender/'+str(pedid.id))
    except:
        return redirect('/ventas/vender/'+str(pedid.id))
     
def editarLinea(request, idLinea):
    linea=lineaDeVenta.objects.get(id=int(idLinea))
    if request.method == 'POST':
        form = agregar(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            pedid=linea.pedidofk
            pedid.quitar(linea.getSubtotal())
            linea.setCantidad(form_data.get("cantidad"))
            linea.sub()
            linea.save()
            pedid.setTotal(linea.getSubtotal())
            pedid.save()
            try:
                renta=Renta.objects.get(id=pedid.renta.id)
                renta.calcular(pedid.total)           
                renta.totalPagar=pedid.total+renta.pagoIva            
                renta.save()
                return redirect('/ventas/vender/'+str(linea.pedidofk.id))
            except:
                return redirect('/ventas/vender/'+str(linea.pedidofk.id))
    else:
        form=agregar()
        content={'form':form,'linea':linea}
    return render(request,'ventas/venta/editar.html',content)

def agregarLinea(request,idPedido,idProducto):
    pedid=pedido.objects.get(id=int(idPedido))
    prod=Producto.objects.get(id=int(idProducto))
    if request.method == 'POST':
        form=agregar(request.POST)
        if form.is_valid():
            form_data=form.cleaned_data
            linea=lineaDeVenta()
            linea.setArticulo(prod)
            linea.setCantidad(int(form_data.get("cantidad")))
            linea.setPedido(pedid)
            linea.sub()
            linea.save()
            pedid.setTotal(linea.getSubtotal())
            pedid.save()
            try:
                renta=Renta.objects.get(id=pedid.renta.id)
                renta.calcular(pedid.total)    
                renta.totalPagar=pedid.total+renta.pagoIva                   
                renta.save()
                ruta='/ventas/vender/'+str(pedid.id)
                return redirect(ruta)
            except:
                ruta='/ventas/vender/'+str(pedid.id)
                return redirect(ruta)
    else:
        form=agregar()
        variables={'form':form,'pedid':pedid,'prod':prod}
        return render (request,'ventas/venta/agregar.html',variables)

def iniciarVenta(request):
    if request.method =='POST':
        form=iniciarVe(request.POST)
        if form.is_valid():            
            form_data=form.cleaned_data
            venta=pedido()
            venta.setCliente(form_data.get("cliente"))
            if(form_data.get("credito")==True):
                renta = Renta()
                renta.save()
                venta.setRenta(renta)
                venta.save()
            else:
                venta.save()
            ruta='/ventas/vender/'+str(venta.id)
            return redirect(ruta)
    else:
        form=iniciarVe()
        return render(request,'ventas/venta/iniciarVenta.html',{'form':form})



@login_required
def informe_meta_diaria(request):
    mes_actual = datetime.now().month
    anio_actual = datetime.now().year
    dia_actual = datetime.now().day

    #obtiene el total de las ventas realizadas por empledado en un tiempo especifico
    meta_diaria = Asignacion.objects.filter(tipo_meta=1)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  
    
    return render(request,'ventas/informes/empleado_meta_diaria.html',
    {'totales':totales,'meta_diaria':meta_diaria,'anio':anio_actual,'mes':mes_actual,'dia':dia_actual})

@login_required
def informe_meta_diaria_pdf(request):
    template_path = 'ventas/informes/ventas_meta_diaria_pdf.html'

    anio_actual = datetime.now().year
    meta_diaria = Asignacion.objects.filter(tipo_meta=1)
    
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  

    context = {'totales':totales,'meta_diaria':meta_diaria}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@login_required
def informe_meta_quincenal(request):
    mes_actual = datetime.now().month
    anio_actual = datetime.now().year
    dia_actual = datetime.now().day

    #obtiene el total de las ventas realizadas por empledado en un tiempo especifico
    meta_diaria = Asignacion.objects.filter(tipo_meta=2)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  
    
    return render(request,'ventas/informes/empleado_meta_quincenal.html',
    {'totales':totales,'meta_diaria':meta_diaria})

@login_required
def informe_meta_quincenal_pdf(request):
    template_path = 'ventas/informes/ventas_meta_quincenal_pdf.html'

    anio_actual = datetime.now().year
    meta_diaria = Asignacion.objects.filter(tipo_meta=2)
    totales = pedido.objects.filter(
        fechaCreada__year=anio_actual).values(
            'vendedor','vendedor__nombres','vendedor__apellidos','vendedor__id').annotate(Sum('total'))  

    context = {'totales':totales,'meta_diaria':meta_diaria}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)

templates/ventas/venta/agregar.html
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
<form action="{% url 'ventas:añadir' pedid.id prod.id%}" method='POST'>
{% csrf_token %}
{{form.as_p}}
<button type="submit">Añadir Productos</button>
</form>

templates/ventas/venta/confirmar.html
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
<form action="{% url 'ventas:finalizar' ped.id %}" method='POST'>
{% csrf_token %}
{{form.as_p}}
<button type="submit">Confirmar Venta</button>
</form>

templates/ventas/venta/editar.html
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
<form action="{% url 'ventas:editar' linea.id%}" method='POST'>
{% csrf_token %}
{{form.as_p}}
<button type="submit">Actualizar</button>
</form>

templates/ventas/venta/factura.html
{% extends 'base/b_sistema.html' %}
{% load static %}
{% block title %}SIAVAC | Factura{% endblock %}
{% block navegacion %}
<style type="text/css"> 
  input[type=text] {
  width: 150px;
  
}
</style>
<nav class="main-nav float-right d-none d-lg-block">
<ul>
    <li><a href="{% url 'ventas:sinFinalizar' %}">Ventas Pendientes</a></li>
    {% if pedid.total > 0 %}
         <li><a href="{% url 'ventas:finalizar' pedid.id %}" rel="get:id=10" rev="abcwin[500,500]">Finalizar Venta</a></li>
    {% endif %}
   
    <li><a href="{% url 'ventas:cancelar' pedid.id %}">Cancelar Venta</a></li>
</ul>
 </nav><!-- .main-nav -->
{% endblock navegacion %}

{% block propio %}
    {% block errorContra %}
    {% if error == True %}
    <h4>¡Contraseña errónea! Favor introducirla correctamente.</h4>
    {% endif %}
    {% endblock errorContra %}
    
    <div>
        <h2>{% block titulo_contenido %}Factura{% endblock titulo_contenido%}</h2>
        <table align="left">
  <tr>
    <th style="width:180px">Cliente:</th>
    <td>{{pedid.cliente}}</td>
  </tr>
  <tr>
    <th>Fecha de Facturación:</th>
    <td>{{pedid.fechaCreada}}</td>
  </tr>
  <tr>
    <th>Total Actual:</th>
    <td>${{pedid.total}}</td>
  </tr>
  {% if renta %}
  <tr>
    <th>crédito fiscal</th>
    <td>${{renta.pagoIva }}</td>
  </tr>
  <tr>
    <th>Total a cancelar</th>
    <td>{{ renta.totalPagar }}</td>
  </tr>
  {% endif %}
  <tr>
  </tr>
</table>

        <div>
        </div>
        <div>
        <table table class="table" id="proveedor-table" >
        <caption>Productos a comprar</caption>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% if lineas %}
          {% for linea in lineas %}
            <tr>
                <td>{{linea.articulofk.nombre}}</td>
                <td>${{linea.articulofk.precioventa}}</td>
                <td>{{linea.cantidad}}</td>
                <td>${{linea.subtotal}}</td>
                <th>
                <a href="{% url 'ventas:editar' linea.id %}" rel="get:id=10" rev="abcwin[500,500]"><img src="/static/images/editar.png" title="Editar" width="20" height="20"/></a>
                <a href="{% url 'ventas:eliminar' linea.id %}"><img src="/static/images/delete.png" title="Editar" width="20" height="20"/></a>
            </tr>
          {% endfor %}
        </tbody>

        {% endif %}
        </table><br>
        </div>

        <div>
       <table table class="table" id="proveedor-table">
        <caption>Stock</caption>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Stock</th>
                <th>Acción</th>
                <th><form method="post"> 
                      {% csrf_token %} 
                      <input type="text" placeholder="Buscar Producto" name="buscar" value="{{request.GET.buscar }}" width=50px> 
                      <button type="submit" class="btn btn-primary btn btn-primary">Buscar</button>
                      <button type="submit" class="btn btn-primary btn btn-primary" onclick="location.reload();">Actualizar</button> 
                    </form> </th>
            </tr>
        </thead>
        <tbody>
        {% if productos %}
           {% for producto in productos %}
            <tr>
                <td>{{producto.nombre}}</td>
                <td>{{producto.descripcion}}</td>
                <td>${{producto.precioventa}}</td>
                <td>{{producto.existencia}}</td>
                <td> <a href= {% url 'ventas:añadir' pedid.id producto.id %} rel="get:id=10" rev="abcwin[500,500]"> Añadir</a>
            </tr>
          {% endfor %}
        {% endif %}
        </tbody>
        </table>
        </div>
    </div>
{% endblock propio %}

templates/ventas/venta/iniciarVenta.html
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
          
	<form action="{% url 'ventas:iniciar' %}" method="POST" class="js-meta-update-form">	
		{%csrf_token%}
		{{form.as_p}}
		<button type="submit" class="btn btn-primary">Iniciar</button>
	</form>

templates/ventas/venta/sinFinalizar.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Ventas{% endblock %}
{% block titulo_contenido %}Ventas sin Finalizar{% endblock titulo_contenido%}
{% block previa_contenido %}Se presentan las ventas registradas que aún están pendientes por finalizar.{% endblock previa_contenido%}
{% block inf %}
Continue una venta en específico haciendo click en el ícono <img src="/static/images/continuar.png" title="Editar" width="20" height="20"/> al lado de la venta seleccionada o elimine una venta sin finalizar haciendo click en el ícono <img src="/static/images/delete.png" title="Editar" width="20" height="20"/> Elimine todas las ventas sin finalizar de la tabla haciendo click en:  <p style="text-align:center"><a href="{% url 'ventas:eliminarPendientes' %}"><button type="button" class="btn btn-primary js-create-proveedor">Eliminar todas las ventas</button></a></p> 

Regrese al menú principal seleccionando: <p style="text-align:center"><br><a href="/"><button type="button" class="btn btn-primary js-create-proveedor">Regresar Menú Anterior</button></a></p>
{% endblock inf%}
{% block navegacion %}
{% endblock navegacion %}
{% block content %}

          <table table class="table" id="proveedor-table">
                <thead>
                    <tr>
                        <th>Vendedor</th>
                        <th>Cliente</th>
                        <th>Total</th>
                        <th>Fecha</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for pedido in  pedidos%}
                     <tr>
                        <td>{{pedido.vendedor.nombres}}</td>
                        <td>{{pedido.cliente}}</td>
                        <td>{{pedido.total}}</td>
                        <td>{{pedido.fechaCreada. }}</td>
                        <td><a href="{% url 'ventas:cancelar' pedido.id %}"><img src="/static/images/delete.png" title="Eliminar" width="20" height="20"/></a><a href="{% url 'ventas:vender' pedido.id %}"><img src="/static/images/continuar.png" title="Eliminar" width="20" height="20"/></a>
                    </tr>
                {% endfor %}
                   
                </tbody>
          </table>

{% endblock content %}