apps/compras/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.urls import path
from django.conf.urls import url
from apps.compras.views import *

app_name='compras'
urlpatterns=[
    url(r'^cancel/(?P<idPedido>\w+)',cancelarPedido,name="cancel"),
    url(r'^aceptar/(?P<idPedido>\w+)',recibirPedido,name="aceptar"),
    url(r'^index',verpedidos,name="index"),
    url(r'^realizarCompras',agregarPedido,name="reCom"),
    url(r'^add/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', agregarLinea,name="add"),
    url(r'^editar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', editarLinea,name="editarLinea"),
    url(r'^borrar/(?P<idLinea>\w+)/(?P<idPedido>\w+)/(?P<producto>\w+)/(?P<idProveedor>\w+)', borrarLinea,name="borrarLinea"),
    #url(r'^addPedido', agregarPedido, name="addP"),
    url(r'^pedir/(?P<idPedido>\w+)/(?P<idProveedor>\w+)/', lineapedido, name="lin"),
    url(r'^cancelar/(?P<idPedido>\w+)/', cancelar, name="cancelar"),
    url(r'^verDetalle/(?P<idPedido>\w+)/', verDetalle, name="verDetalle"),
    url(r'^gestionarPedidos',PedidosList,name="gesPed"),
    
    path(
    	'proveedor/', 
    	proveedor_list,
    	name='proveedor-list'
    ),
    path(
    	'proveedor/create/',
    	proveedor_create,
    	name='proveedor-create'
    ),
    path(
        'proveedor/update/<int:pk>',
        proveedor_update,
        name='proveedor-update'
    ),
    path(
        'proveedor/delete/<int:pk>',
        proveedor_delete,
        name='proveedor-delete'
    ),


    path(
    	'articulo/', 
    	articulo_list,
    	name='articulo-list'
    ),
    path(
    	'articulo/create/',
    	articulo_create,
    	name='articulo-create'
    ),
    path(
        'articulo/update/<int:pk>',
        articulo_update,
        name='articulo-update'
    ),
    path(
        'articulo/delete/<int:pk>',
        articulo_delete,
        name='articulo-delete'
    ),

]

dsi115/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('seguridad/',include('apps.seguridad.urls')),
    path('inventario/',include('apps.inventario.urls')),
    path('compras/',include('apps.compras.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('', RedirectView.as_view(url='/seguridad/login', permanent=False)),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

apps/compras/forms.py
from django import forms 
from apps.inventario.models import *
from .models import *

#class ProveedorForm(forms.ModelForm):
#	class Meta:
#		model = Proveedor
#		fields = ('nombre', 'direccion', 'mobile', 'email',)

#class ArticuloForm(forms.ModelForm):
#	class Meta:
#		model = Producto
#		fields = ('nombre', 'precioCompra', 'proveedor', 'precioVenta','existencia','descripcion')

prove=Proveedor.objects.all()
tipos=Tipo_Pago.objects.all()

class comentarioPedido(forms.Form):
	comentario=forms.CharField(label="Nota especial",max_length=50,required=False)

class pedidoForm(forms.Form):
	proveedores=forms.ModelMultipleChoiceField(prove,required=True)
	tipo=forms.ModelMultipleChoiceField(tipos,required=True)
	
class formulario(forms.Form):
	cantidad=forms.IntegerField(required=True)
	comentario=forms.CharField(label="Nota especial",max_length=50,required=False)

class ProveedorForm(forms.ModelForm):
	class Meta:
		model = Proveedor
		fields = ('nombre', 'telefono', 'direccion','nombreRepresentante','telefonoPersonal')
		labels={
			'nombre':'Nombre del Proveedor',
			'telefono':'Telefono',
			'direccion':'Dirección',
			'nombreRepresentante':'Nombre del vendedor',
			'telefonoPersonal':'teléfono personal',
		}
		widgets={
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'telefono' : forms.TextInput(attrs={'class':'form-control'}),
			'direccion' : forms.TextInput(attrs={'class':'form-control'}),
			'nombreRepresentante' :   forms.TextInput(attrs={'class':'form-control'}),
			'telefonoPersonal' :   forms.TextInput(attrs={'class':'form-control'}),
		}

class ArticuloForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = [
			'nombre', 
			'descripcion', 
			'precioventa', 
			'preciocompra',
			'existencia',
			'promocion',
			'fkproveedor',
			'fkcategoria',
			'minimo',
		]
		labels={
			'nombre':'Nombre Articulo',
			'descripcion':'Descripción',
			'precioventa':'Precio de Venta',
			'preciocompra':'Precio de Compra',
			'existencia':'Existencia',
			'promocion':'Promocion',
			'fkproveedor':'Proveedor',
			'fkcategoria':'Categoria',
			'minimo':'cantidad mínima de producto',
		}
		widgets={
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'descripcion' : forms.TextInput(attrs={'class':'form-control'}),
			'precioventa' : forms.NumberInput(attrs={'class':'form-control'}),
			'preciocompra' : forms.NumberInput(attrs={'class':'form-control'}),
			'existencia' : forms.NumberInput(attrs={'class':'form-control'}),
			#'promocion' : forms.ChoiceField(attrs={'class':'form-control'}),
			'fkproveedor' : forms.Select(attrs={'class':'form-control'}),
			'fkcategoria' : forms.Select(attrs={'class':'form-control'}),
			'minimo' : forms.NumberInput(attrs={'class':'form-control'}),
		}


'''
class pedidoForm(forms.ModelForm):

	#def __init__(self, request,*args,**kwargs):
	#	super(pedidoForm,self).__init__(*args,**kwargs)
	#	self.fields['proveedor'].queryset = (detalle_Pedido.fkProducto).objects.filter(fkProducto=Producto.id)

	class Meta:
		model = detalle_Pedido
		fields=[
			'fkProducto',
			'fkPedido',
			'cantidad',
		#	'comentario',
		]
		labels={
			'fkProducto':'Producto',
			'fkProovedor':'Proovedor',
			'cantidad':'Cantidad',
		#	'comentario':'Comentario',
		}
		widgets={
			#'fkProducto' : forms.ChoiceField(attrs={'class':'form-control'}),
			#'fkProovedor' : forms.Select(),
			#'cantidad' : forms.IntegerField(),
		#	'comentario' : forms.CharField(),
		}
'''

apps/compras/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from random import randrange, choice
#librerias usadas para articulo y proveedor
from .forms	import *
from datetime import date
from django.views.generic import *
from apps.inventario.models import Proveedor, Producto
from apps.compras.models import *
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from .forms import *
from django.template.loader import render_to_string
from django.urls import reverse_lazy
# Create your views here.
#falta agregar verificación por rol
@login_required
def indexCompras(request):
	return render(request,'compras/gestionar_pedidos.html')

@login_required
def proveedor_list(request):
	proveedors = Proveedor.objects.all()
	return render(request,'compras/proveedor/proveedor_list.html',{'proveedors':proveedors})


@login_required
def save_proveedor_form(request, form, template_name):
	data = dict()
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			data['form_is_valid']=True
			proveedors = Proveedor.objects.all()
			data['html_proveedor_list'] = render_to_string('compras/proveedor/proveedor_list_2.html',
				{'proveedors':proveedors})
		else:
			data['form_is_valid']=False
	context = {'form':form}
	data['html_form'] = render_to_string(
		template_name,
		context,
		request = request,
	)
	return JsonResponse(data)

@login_required
def proveedor_create(request):
    if request.method == 'POST':
        form = ProveedorForm(request.POST)
    else:
        form = ProveedorForm()
    return save_proveedor_form(request, form, 'compras/proveedor/proveedor_create.html')


@login_required
def proveedor_update(request, pk):
    proveedor = get_object_or_404(Proveedor, pk=pk)
    if request.method == 'POST':
        form = ProveedorForm(request.POST, instance=proveedor)
    else:
        form = ProveedorForm(instance=proveedor)
    return save_proveedor_form(request, form, 'compras/proveedor/proveedor_update.html')
    
@login_required
def proveedor_delete(request, pk):
    proveedor = get_object_or_404(Proveedor, pk=pk)
    data = dict()
    if request.method == 'POST':
        proveedor.delete()
        data['form_is_valid'] = True  
        proveedors = Proveedor.objects.all()
        data['html_proveedor_list'] = render_to_string('compras/proveedor/proveedor_list_2.html', {
            'proveedors': proveedors
        })
    else:
        context = {'proveedor': proveedor}
        data['html_form'] = render_to_string('compras/proveedor/proveedor_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

@login_required
def articulo_list(request):
	articulos = Producto.objects.all()
	return render(request,'compras/articulo/articulo_list.html',{'articulos':articulos})

@login_required
def save_articulo_form(request, form, template_name):
	data = dict()
	if request.method == 'POST':
		#form = ArticuloForm(request.POST)
		if form.is_valid():
			form.save()
			data['form_is_valid']=True
			articulos = Producto.objects.all()
			data['html_articulo_list'] = render_to_string('compras/articulo/articulo_list_2.html',
				{'articulos':articulos})
		else:
			data['form_is_valid']=False
	context = {'form':form}
	data['html_form'] = render_to_string(
		template_name,
		context,
		request = request,
	)
	return JsonResponse(data)

@login_required
def articulo_create(request):
    if request.method == 'POST':
        form = ArticuloForm(request.POST)
    else:
        form = ArticuloForm()
    return save_articulo_form(request, form, 'compras/articulo/articulo_create.html')

@login_required
def articulo_update(request, pk):
    articulo = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        form = ArticuloForm(request.POST, instance=articulo)
    else:
        form = ArticuloForm(instance=articulo)
    return save_articulo_form(request, form, 'compras/articulo/articulo_update.html')
@login_required
def articulo_delete(request, pk):
    articulo = get_object_or_404(Producto, pk=pk)
    data = dict()
    if request.method == 'POST':
        articulo.delete()
        data['form_is_valid'] = True  
        articulos = Producto.objects.all()
        data['html_articulo_list'] = render_to_string('compras/articulo/articulo_list_2.html', {
            'articulos': articulos
        })
    else:
        context = {'articulo': articulo}
        data['html_form'] = render_to_string('compras/articulo/articulo_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

@login_required
def verpedidos(request):
	pedidos=Pedido.objects.all().order_by('-fechaPedido')
	contexto = {'pedidos':pedidos}
	return render(request, 'compras/pedidos/gestionar_pedidos.html',contexto)

def verDetalle(request,idPedido):
    lineas = detalle_Pedido.objects.all().filter(fkPedido=idPedido)
    pedido = Pedido.objects.get(id=idPedido)
    contexto={'lineas':lineas,'pedido':pedido}
    return render(request,'compras/pedidos/verDetalle.html',contexto)


#def crearPedido(request):
@login_required
def lineapedido(request, idPedido, idProveedor):#muestra los productos dle proveedor y da pauta para añadir
    cat=Categoria.objects.get(id=idProveedor)
    produc=Producto.objects.all().filter(fkcategoria= cat)
    detalle=detalle_Pedido.objects.all().filter(fkPedido=Pedido.objects.get(id=idPedido))
    var=detalle.count()
    return render(request,'compras/pedidos/realizar_pedido.html',{'productos':produc,'idPedido':idPedido,'idProveedor':idProveedor,'detalle':detalle,'var':var})

@login_required
def cancelar(request, idPedido):
    pedido=Pedido.objects.get(id=idPedido)
    detalle=detalle_Pedido.objects.all().filter(fkPedido=pedido)
    detalle.delete()
    pedido.delete()
    return redirect('compras:index')

@login_required
def borrarLinea(request, idLinea, idPedido, producto, idProveedor):
    deta=detalle_Pedido.objects.get(id=int(idLinea))
    pedido=Pedido.objects.get(id=idPedido)
    pedido.quitarSubtotal(deta.getSubtotal())
    pedido.save()
    print(deta.getSubtotal())
   
    cat=Categoria.objects.get(id=idProveedor)
    produc=Producto.objects.all().filter(fkcategoria= cat)
    detalle=detalle_Pedido.objects.all().filter(fkPedido=Pedido.objects.get(id=idPedido))
    var=detalle.count()
    deta.delete()
    return render(request,'compras/pedidos/realizar_pedido.html',{'productos':produc,'idPedido':idPedido,'idProveedor':idProveedor,'detalle':detalle,'var':var})

@login_required
def editarLinea(request, idLinea, idPedido, producto, idProveedor):
    if request.method=='POST':
        fom=formulario(request.POST)
        if fom.is_valid():
            form_data=fom.cleaned_data
            deta=detalle_Pedido.objects.get(id=idLinea)
            deta.delete()
            detalle=detalle_Pedido()
            pedido=Pedido.objects.get(id=idPedido)
            producto=Producto.objects.get(id=producto)
            pedido.quitarSubtotal(detalle.getSubtotal())       
            detalle.setfkPedido(pedido)
            detalle.setfkProducto(producto)
            detalle.setCantidad(form_data.get("cantidad"))
            detalle.setSubtotal()
            pedido.agregarSubtotal(detalle.getSubtotal())
            detalle.setComentario(form_data.get("comentario"))
            detalle.save()
            pedido.save()
            cat=Categoria.objects.get(id=idProveedor)
            produc=Producto.objects.all().filter(fkcategoria= cat)
            detalle=detalle_Pedido.objects.all().filter(fkPedido=Pedido.objects.get(id=idPedido))
            var=detalle.count()
            return render(request,'compras/pedidos/realizar_pedido.html',{'productos':produc,'idPedido':idPedido,'idProveedor':idProveedor,'detalle':detalle,'var':var})
    else:
        form=formulario()
        contexto={'form':form,'producto':producto,'idPedido':idPedido,'idProveedor':idProveedor,'idLinea':idLinea}
        return render(request,'compras/pedidos/realizar_pedido.html',contexto)
@login_required
def cancelarPedido(request, idPedido):
    if request.method=='POST':
        fomu=comentarioPedido(request.POST)
        if fomu.is_valid():
            form_data=fomu.cleaned_data
            pedido =  Pedido.objects.get(id=idPedido)
            pedido.comentario=form_data.get("comentario")
            pedido.cancelado=True
            pedido.pendiente=False
            pedido.save()
            urlss='/compras/verDetalle/'+idPedido
            return redirect(urlss)
    else:
        form=comentarioPedido()
        return render(request,'compras/pedidos/comentario.html',{'form':form,'idPedido': idPedido})

@login_required
def recibirPedido(request, idPedido):
    if request.method=='POST':
        fomu=comentarioPedido(request.POST)
        if fomu.is_valid():
            form_data=fomu.cleaned_data
            pedido =  Pedido.objects.get(id=idPedido)
            lineas = detalle_Pedido.objects.all().filter(fkPedido=idPedido)
            for linea in lineas:
                producto = Producto.objects.get(id=linea.fkProducto.id)
                producto.agregarInventario(linea.cantidad)
                producto.save()
            pedido.comentario=form_data.get("comentario")
            pedido.exito = True
            pedido.pendiente = False
            pedido.save()
            urlss='/compras/verDetalle/'+idPedido
            return redirect(urlss)
    else:
        form=comentarioPedido()
        return render(request,'compras/pedidos/comentario2.html',{'form':form,'idPedido': idPedido})


@login_required
def agregarPedido(request):#genera el pedido
    if request.method=='POST':
        fomu=pedidoForm(request.POST)
        if fomu.is_valid():
            form_data=fomu.cleaned_data
            pedido=Pedido()
            pedido.save()
            pago=Pago()

templates/compras/pedidos/agregar_articulo.html
{% load static%}
{% block css %}
 	<script type="text/javascript" src="/static/js/scriptA.js"></script>
 {% endblock css %}
{%block contenido%}
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
			<h3>Edición de pedidos</h3>
 
 		<form action="{% url 'compras:add' idPedido producto idProveedor%}" method='POST'>
 			{% csrf_token %}
 			{{form.as_p}}
			<button type="submit" value="submit" class="boton3">Agregar línea</button>

			<br><a href="{% url 'compras:lin' idPedido idProveedor %}"><button class="boton3">Cancelar línea</button></a>
 		</form>
	
{%endblock contenido%}

templates/compras/pedidos/comentario.html
<form action="{% url 'compras:cancel' idPedido %}" method="POST" id="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit" id="submit" class="boton">Generar pedido</button>
</form>

templates/compras/pedidos/comentario2.html
<form action="{% url 'compras:aceptar' idPedido %}" method="POST" id="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit" id="submit" class="boton">Generar pedido.</button>
</form>

templates/compras/pedidos/editar.html
{% load static%}
{% block css %}
 	<link rel="stylesheet" type="text/css" href="{% static "css/cssA.css" %}">
 	<script type="text/javascript" src="/static/js/scriptA.js"></script>
 {% endblock css %}
{%block contenido%}

 <div class="contenedor2">
            <div id="contenido2">

			<h1><label> Edición de pedido</label></h1>
<h3>
</h3>
 <div id="principal">
 	<div id="izquierda">
 		<form action="{% url 'compras:editarLinea' idLinea idPedido producto.id idProveedor%}" method='POST'>
 			{% csrf_token %}
 			{{form.as_p}}
			<button type="submit" value="submit" class="boton3">Agregar línea</button>
 		</form>
	</div>
 	<div id="derecha">
 		<div>
 			<button class="boton3" onclick="incrementar()">+</button>
			<button class="boton3" onclick="decrementar()">-</button>
 		</div>
 		
 	</div>
 </div>
 <footer>
 			<a href="{% url 'compras:lin' idPedido idProveedor %}"><button class="boton3">Cancelar</button></a>
 		</footer>

			</div>
 </div>

	
{%endblock contenido%}

templates/compras/pedidos/generar_pedidos.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Pedidos{% endblock %}
{% block titulo_contenido %}Crear Nuevo Pedido{% endblock titulo_contenido%}
{% block previa_contenido %}Genere un nuevo pedido con el proveedor, forma de pago y productos que necesite.{% endblock previa_contenido%}
{% block inf %}
Luego de seleccionar el proveedor y la forma de pago que desee, haga click en <strong>Generar Pedido</strong> para continuar con el proceso de pedido o en <strong>Cancelar</strong> para regresar al menú principal.
<p style="text-align:center"><a href="{% url 'compras:index' %}"><button type="button" class="btn btn-primary js-create-proveedor">Cancelar</button></a></p>
{% endblock inf%}
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/css/cssE.css"/>
<form action="{% url 'compras:reCom' %}" method="POST" id="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit" id="submit" class="boton">Generar pedido</button>
</form>

{% endblock content%}

templates/compras/pedidos/gestionar_pedidos.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Pedidos{% endblock %}
{% block titulo_contenido %}Pedidos Realizados{% endblock titulo_contenido%}
{% block previa_contenido %}Se presentan los pedidos registrados así como la opción ver detalles para mostrar más información sobre el pedido seleccionado.{% endblock previa_contenido%}
{% block inf %}


Cree un nuevo pedido o gestione la información relacionada con los proveedores seleccionando una de las siguientes opciones: 
<p><a href="{% url 'compras:reCom' %}"><button type="button" class="btn btn-primary js-create-proveedor">Crear Pedido</button></a>
<a href="/compras/proveedor"><button type="button" class="btn btn-primary js-create-proveedor">Gestionar Proveedores</button></a></p>
{% endblock inf%}

{% block content %}
{%if pedidos%}
<table class="table" id="proveedor-table">
	<thead>
		<tr>
			<td>Fecha de Creación</td>
			<td>Proveedor</td>
			<td>Monto</td>
			<td>Estado</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
		
		{%for pedido in pedidos%}
		<tr>
			<td>{{pedido.fechaPedido}}</td>
			<td>{{pedido.fkProveedor.nombre}}</td>
			<td>{{pedido.subtotal}}</td>
			{% if pedido.pendiente == True%}
			<td>Pendiente</td>
			{% elif pedido.cancelado == True%}
			<td>Cancelado</td>
			{% else%}
			<td>Recibido</td>
			{% endif%}
			
			<td><a href="{% url 'compras:verDetalle' pedido.id %}">Ver detalle</a></td>
		</tr>
		{%endfor%}
		
	</tbody>
</table>
{%else%}
		<label><h3>No hay pedidos registrados</h3><p>Para ingresar un nuevo pedido, seleccione la opción <strong>Generar Pedido</strong> e ingrese los datos que se le solicitarán.</p></label>
		{%endif%}

{% endblock %}

templates/compras/pedidos/realizar_pedido.html
{% extends 'base/base_sistema.html' %}
{% block title %}SIAVAC | Nuevo Pedido{% endblock %}
{% block titulo_contenido %}Crear Nuevo Pedido{% endblock titulo_contenido%}
{% block previa_contenido %}Se muestran los productos que ofrece el proveedor y los añadidos al pedido.{% endblock previa_contenido%}
{% block inf %}
Se mostrará una tabla con todos los productos que ofrece el proveedor, seleccione los que desee así como las unidades que necesita adquirir. Puede agregar una nota especial, de considerarlo necesario.
<p style="text-align:center"><a href="{% url 'compras:cancelar' idPedido%}"><button type="button" class="btn btn-primary js-create-proveedor">Cancelar Pedido</button> </a></p>
{%if var != 0%}
<p style="text-align:center"><a href="{% url 'compras:index' %}"><button type="button" class="btn btn-primary js-create-proveedor">Terminar Pedido</button> </a></p>
{%endif%}

{% endblock inf%}

{%block content%}
<link rel="stylesheet" type="text/css" href="/static/css/ABCwin.css"/>
<script type="text/javascript" src="/static/js/ABCwin.js"></script>
<table class="table" id="proveedor-table">
	<thead>
		<tr>
			<td>Nombre</td>
			<td>Precio</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
		{%if productos%}
			{%for producto in productos%}
				<tr>
					<td>{{producto.nombre}}</td>
					<td>{{producto.preciocompra}}</td>
					<td> <a href="{% url 'compras:add' idPedido producto.id idProveedor%}" rel="get:id=10" rev="abcwin[500,auto]">Agregar</a> </td>
				</tr>
			{%endfor%}
		{%else%}
			<h3>No tenemos productos de este Proveedor.</h3>
		{%endif%}
	</tbody>
</table>

<label><h3><strong>Productos Seleccionados</strong></h3></label>
<table class="table" id="proveedor-table">
	<thead>
		<tr></tr>
		<tr>
			<td>Artículo</td>
			<td>Cantidad</td>
			<td>Subtotal</td>
			<td>Comentario</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
	{%if detalle%}
			{%for detalle in detalle%}
	
		
				<tr>
					<td>{{detalle.fkProducto.nombre}}</td>
					<td>{{detalle.cantidad}}</td>
					<td>{{detalle.subtotal}}</td>
					<td>{{detalle.comentario}}</td>
					<td><a href="{% url 'compras:borrarLinea'  detalle.id idPedido detalle.fkProducto.id idProveedor %}">Eliminar</td>
					
				</tr>
			{%endfor%}
		{%else%}
			<label><h3>Aún no se ha registrado nada en el pedido</h3><p>Para agregar un artículo al pedido, seleccione un producto de la tabla de arriba y haga click en <strong>agregar</strong>. Luego, ingrese los datos que se le solicitarán.</p></label>
		{%endif%}
	</tbody>
</table>
{%endblock content%}

templates/compras/pedidos/verDetalle.html
{% extends 'base/base_sistema.html' %}
{% block content %}
<h1>Detalle de pedido</h1>
<div>
<table class="table">
    <tr>
        <td>Proveedor</td>
        <td> {{pedido.fkProveedor}}</td>
    </tr>
    <tr>
        <td>Fecha del pedido</td>
        <td> {{ pedido.fechaPedido}}</td>
    </tr>
    <tr>
        <td>Total a cancelar</td>
        <td>  {{pedido.subtotal}}</td>
    </tr>
    <tr>
        <td>Estado</td>
        <td>
            {% if pedido.pendiente == True%}
			Pendiente
			{% elif pedido.cancelado == True%}
			Cancelado
			{% else%}
			Recibido
			{% endif%}  
        </td>
    </tr>
    <tr>
            {% if pedido.pendiente == True%}
			<td>Acciones</td>
            <td><a href="{% url 'compras:cancel' pedido.id %}" rel="get:id=10" rev="abcwin[500,auto]">Cancelar pedido </a></td>
            <td><a href="{% url 'compras:aceptar' pedido.id %}" rel="get:id=10" rev="abcwin[500,auto]">Marcar como recibido</a></td>
			{% elif pedido.cancelado == True%}
			<td>Razon de cancelado</td>
            <td>{{pedido.comentario}}
			{% else%}
			<td>Comentario de recibido</td>
            <td>{{pedido.comentario}}
			{% endif%}  
        
    </tr>
       
</div>
<table class="table">
<thead>
    <th>Producto</th>
    <th>Cantidad</th>
    <th>Precio unitario</th>
    <th>Subtotal</th>
</thead>
<tbody>
<tr>
    {% if lineas%}
    {% for linea in lineas%}
        <td>{{ linea.fkProducto.nombre}}</td>
        <td>{{ linea.cantidad }} </td>
        <td>{{ linea.fkProducto.preciocompra}}</td>
        <td> {{ linea.subtotal}} </td>
        <td></td>

    {% endfor %}
    {% else %}
    <h3>No hay lineas agregadas</h3>
    {% endif %}
</tr>
</tbody>
</table>
{% endblock content %}